services:
  - type: web
    name: product-api
    env: dotnet
    runtime: dotnet
    buildCommand: "curl -sSL https://dot.net/v1/dotnet-install.sh | bash && export PATH=$HOME/.dotnet:$PATH && dotnet restore && dotnet build"
    startCommand: "dotnet run"
    plan: free
    region: frankfurt